### PR TITLE
Update README

### PR DESCRIPTION
**Pull request by GreemDev**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [ ] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Changed up some wording, removed unnecessary hyphens, etc.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Please rebase your changes on docs/development

**Comment by GreemDev** [comment]
Gonna open a new PR to target docs/development from GreemDev/JDA:docs/development

**Comment by DManstrator** [comment]
Afaik, you can update the target branch later on, can't you? At least I saw Minn changing it sometimes.

**Comment by GreemDev** [comment]
> Afaik, you can update the target branch later on, can't you? At least I saw Minn changing it sometimes.

He changed the target; not the source branch. I'm pretty sure that was the issue

**Comment by DManstrator** [comment]
Oh yeah, just saw it. My bad.

**Pull request closed without merging**
