### PR TITLE
Auxiliary support

### PR DESCRIPTION
**Pull request by Almighty-Alpaca**
You wanted it :exclamation:

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
A+, Needs more javadoc though.

**Comment by mcNETDev** [comment]
what is a Auxiliary Cable?
System audio line?

**Comment by kantenkugel** [comment]
[See here](http://i.ebayimg.com/00/s/NDc3WDUwMA==/z/8rYAAMXQ74JTVku4/$_35.JPG?set_id=2)

**Comment by DinosParkour** [comment]
[See here](https://www.youtube.com/watch?v=dQw4w9WgXcQ)

**Pull request merged**
