### PR TITLE
Remove all Presence related idle methods

### PR DESCRIPTION
**Pull request by RedcodesDev**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This PR removes all idle related methods for Presences, as this endpoint is not in use for bots anymore.

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
How do you know this isn't used for bots anymore?

**Comment by RedcodesDev** [comment]
This is not documented anywhere in the Discord docs and I couldn't find any information about the idle parameter for Discord Rich Presences or Statuses/Activities. I would assume that this parameter is from the old client account days of the JDA.

**Comment by TopiSenpai** [comment]
this field is documented here and named `afk` in the API <https://discord.com/developers/docs/topics/gateway#update-presence-gateway-presence-update-structure>

**Comment by DV8FromTheWorld** [comment]
So in conclusion this field is still available in the API?

**Comment by DV8FromTheWorld** [comment]
Going to close this given conversation. Feel free to reopen if I've missed something.

**Pull request closed without merging**
