### PR TITLE
Add jump-to URL for Messages

### PR DESCRIPTION
**Pull request by jagrosh**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

## Description

Adds Message#getJumpUrl() for Messages received from Discord. This is the same link that can be copied from the message menu item Copy Link.

### CODE REVIEW

**Comment by kantenkugel** [comment]
I would like to wait on this a little bit until this is properly added (finalized and documented) on discords end. I have the feeling that the url might still change or that there might be a better url for the future.

**Comment by jagrosh** [comment]
I agree; there might also be additionally functionality that hasn't arrived yet.

**Comment by Artuto** [comment]
Will this be merged? No new functionallity has arrived.

**Comment by Sanduhr32** [comment]
Hey Kantenkugel, I did some research to that topic.

1. The "new" pattern is the initial pattern which was introduced by the Alpha Build of the Discord Android app.
2. Jump-links to *connected* voice channels open the video interface and allow sharing videos in guilds. (Am researching if there are any related events that make the voice chat a video chat for the time people are connected to it and have the video ui open).
I am also unsure if bots receive video data in that case and which format it has that they might provide for music videos or other graphical ways of displaying the audio. (Probably webm).

I hope it helps and informs you a bit about some changes / features that might blast us.
Best regards, Sanduhr32

**Comment by kantenkugel** [comment]
Yea. I think the only thing that needs to be done is to fix the pattern to match the new one (`.../channels/G_ID/C_ID/M_ID`).

@jagrosh do you want to do this (its your PR) or is it better if i do it?

**Comment by MinnDevelopment** [comment]
Are there any other such links that we should consider adding?

**Comment by kantenkugel** [comment]
From my testing i didn't find any. As described in [this comment](https://github.com/DV8FromTheWorld/JDA/pull/700#issuecomment-411868415), we could technically add one for the channel but for that, TextChannel#getAsMention() is better. Discord also renders a ugly embed if that link is used (the jump-to-message one doesn't render an embed; it has custom handling on discords end)

**Pull request merged**
