### PR TITLE
Invite.Group#getUsers now returns usernames

### PR DESCRIPTION
**Pull request by BenjaminUrquhart**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: #965 

## Description

Title says it all

### CODE REVIEW

**Comment by mdashl** [comment]
I don't think this is a valid change,
it should affect EntityBuilder#createInvite

**Comment by BenjaminUrquhart** [comment]
My bad, I'll do it properly in a new PR

**Comment by BenjaminUrquhart** [comment]
My bad, I'll do it properly in a new PR

**Comment by Sanduhr32** [comment]
You dont have to make a new PR. Just revert the changes and push a new commit. PRs are getting squash merged anyways :D

**Pull request closed without merging**
