### PR TITLE
Nullability annotations and cleanup

### PR DESCRIPTION
**Pull request by MinnDevelopment**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

## Description

Parameters annotated with `@NonNull` will display an IDE warning whenever a possibly-null value is passed. Due to `@ParamtersAreNonnullByDefault` we don't have to add this to every parameter, instead we only need to add the special cases where it is nullable using `@Nullable`.

Additionally I fixed a few javadoc issues.

### CODE REVIEW

**Comment by napstr** [comment]
Are there plans to annotate return values too?

**Comment by MinnDevelopment** [comment]
Return values turn out to be a lot more work.

**Comment by MinnDevelopment** [comment]
I've left out most of the events from these changes for now as I needed a break from all of the copy-pasting.

**Comment by MinnDevelopment** [comment]
Return value annotations generate checks and should thus be tested thoroughly before merging.

**Comment by meowingtwurtle** [comment]
~~or just use Kotlin~~

**Comment by MinnDevelopment** [comment]
This is not worth the effort at the moment. I might consider doing this when a bigger portion of the library needs to be rewritten.

**Pull request closed without merging**
