### PR TITLE
Added docs for all the GuildThread methods (excluding GuildThread#get…

### PR DESCRIPTION
**Pull request by Tais993**
…AutoArchiveDuration)

[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [ x] I have checked the PRs for upcoming features/bug fixes.
- [x ] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [x ] Documentation
- [ ] Other: \_____ 

## Description

Added documentation for almost all methods on Guildthread

### CODE REVIEW

**Review by Andre601 — COMMENTED** [review]
Quite a few issues with the styling.
See [JDA Structure Guide](https://github.com/DV8FromTheWorld/JDA/wiki/6%29-JDA-Structure-Guide) about the important stuff.

I only make this a comment because Minn most likely has his own set of changes he requests, so better wait for him to take a look here.

**Review by Tais993 — COMMENTED** [review]
Thanks for reminding me regarding the styling issues, I'll make sure to edit it accordingly

**Comment by Tais993** [comment]
Wops, renamed the branch, didn't knew that closed it

**Review by Tais993 — COMMENTED** [review]
I'd say that a list is more readalbe, is this the correct approach?
I didn't notice lists before in this use-case, so I'm assuming not.

**Comment by Tais993** [comment]
I'm closing this because of some shitty branche management on my side

**Pull request closed without merging**
