### PR TITLE
Add convenience methods for setting only part of the author information in the EmbedBuilder

### PR DESCRIPTION
**Pull request by Vampire**

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
can you fix this to target hacktoberfest properly please

**Comment by kantenkugel** [comment]
yea please base your branch off of hacktoberfest...

**Comment by Vampire** [comment]
Oh, sorry, actually it was a mistake, I wanted to post the PR against master. :-D
I'll rebase, one moment

**Comment by Vampire** [comment]
Ah, I see now that I actually did post against master and you changed it. :-D
My hacktoberfest PRs are already full, but however you like it most. :-)
PR is updated.

**Comment by MinnDevelopment** [comment]
The reason I want to merge this into that branch is because it allows us to make one build for lots of small changes rather than lots of tiny builds

**Comment by Vampire** [comment]
Sure, no problem at all. I know my Git so this was done in no time. :-)

**Pull request merged**
