### PR TITLE
IPermissionHolder Interface

### PR DESCRIPTION
**Pull request by meowingtwurtle**

### CODE REVIEW

**Comment by meowingtwurtle** [comment]
I know that it isn't used anywhere, but I feel that this is a step towards modularity and could be used in several places.

**Comment by DV8FromTheWorld** [comment]
While I agree with the Modularity of it, is there an actual use-case for this?

**Comment by meowingtwurtle** [comment]
The first that would come to mind is that the two maps in the Channels for PermissionOverrides could be merged into one. Several of the canInteract/canTalk things could be updated so that either could be accepted, because sometimes someone may want to check if a Role could use it instead of just a Member.

**Comment by meowingtwurtle** [comment]
It also prepares for possible future permissions systems (unlikely, but not impossible).

**Comment by DV8FromTheWorld** [comment]
Not ignoring this. Will be looking into it more soon. :+1:

**Comment by meowingtwurtle** [comment]
ummmm

**Comment by meowingtwurtle** [comment]
Tried to fix conflicts, ended up breaking something
Will fix later

**Comment by meowingtwurtle** [comment]
FINALLY!

**Pull request merged**
