### PR TITLE
Add new message types for Threads

### PR DESCRIPTION
**Pull request by oliver276**
## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Adds the new message types for threads of THREAD_CREATED and THREAD_STARTER_MESSAGE, as well as documenting the old types that have been repurposed with the release of Threads.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Can you also change the catch here to just catch all exceptions: https://github.com/DV8FromTheWorld/JDA/blob/196f31f25155afdbca3d7e9724aa418437af6125/src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java#L584

And add similar try/catch blocks in these:

https://github.com/DV8FromTheWorld/JDA/blob/196f31f25155afdbca3d7e9724aa418437af6125/src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java#L199

https://github.com/DV8FromTheWorld/JDA/blob/196f31f25155afdbca3d7e9724aa418437af6125/src/main/java/net/dv8tion/jda/api/entities/MessageHistory.java#L268

**Comment by MinnDevelopment** [comment]
There also seems to be `GUILD_INVITE_REMINDER` as `22`, do you have any idea what this is? The docs obviously don't explain anything.

**Comment by oliver276** [comment]
Nope, and as far as I know I haven't encountered it either. I don't have any large bots, so I guess that's to be expected.

Should I add it anyway with the same unhelpful docs as the official docs or should I try to find out its purpose first by trying to ask in ddevs or something?

**Comment by MinnDevelopment** [comment]
For now, I guess just add it with useless docs and we can improve docs once someone knows what it is.

**Comment by fbrettnich** [comment]
In [DiscordDelta](https://github.com/sesaborg/DiscordDelta/wiki/Reference#guild_invite_reminder) it is described as follows:
`GUILD_INVITE_REMINDER` => "A message that serves to remind users that they can invite other users to the guild."

This then looks like this
image

**Review by MinnDevelopment — APPROVED** [review]

**Pull request merged**
