### PR TITLE
Use proper value for shutdown hooks of managed shards

### PR DESCRIPTION
**Pull request by napstr**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

### Pull Request

There's a bug here where the DefaultShardManager is erroneously passing the `enableBulkDeleteSplitting` field as a parameter for enabling shutdown hooks. Instead the value should always be false, since the DefaultShardManager manages the shutdown hook itself.

### CODE REVIEW

**Comment by kantenkugel** [comment]
lgtm, gonna let minn (or better: almighty) merge

**Comment by kantenkugel** [comment]
might wanna change value to true tho (default for standard jda)... dunno

**Comment by napstr** [comment]
The DefaultShardManager uses it's own (configurable) shutdown hook to manage the shards it creates - setting shutdown hooks on the managed shards would be redundant.

**Comment by kantenkugel** [comment]
ok then just ignore my previous comment :)

**Pull request merged**
