### PR TITLE
Remove deprecated classes, methods and fields marked for removal

### PR DESCRIPTION
**Pull request by Alf-Melmac**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

## Description

Removed deprecated classes, methods and fields marked for removal.
Fixed JavaDoc references to deprecated methods.

### CODE REVIEW

**Comment by Alf-Melmac** [comment]
Deprecation that are currently not marked for removal. Should we add a marker or even remove the methods directly?
- GuildAction#setRegion
- GuildAction#getRegionRaw
- GuildUpdateRegionEvent
- GuildManager#setRegion
- PrivateChannel#close

**Comment by DV8FromTheWorld** [comment]
This PR is likely going to enter conflicting states many times before it is merged in.
This is the last thing I'm planning to do before we release a v5 Alpha Release Candidate, so it might be better to hold off until we get closer to then

**Comment by Alf-Melmac** [comment]
I think I've got it all now.

**Comment by Yashar256** [comment]
I see that its planned to make Emojis/Emotes all use a unified Emoji class in the [V5 development roadmap](https://github.com/DV8FromTheWorld/JDA/projects/5#column-15826400). Would this mean that the [Emote](https://github.com/DV8FromTheWorld/JDA/blob/v5/src/main/java/net/dv8tion/jda/api/entities/Emote.java) class will also get removed along with all the other various Emoji/Emote innerclasses?

**Comment by MinnDevelopment** [comment]
@Yashar256 no, the emote class is for custom emoji specifically and offers some additional information such as restricted roles and the emote creator. The planned Emoji class is mainly used to represent name + id and nothing more, such reduced emoji objects are used in reactions/activities/buttons in the API.

**Review by DV8FromTheWorld — COMMENTED** [review]
I've gone through this PR and pulled things out that were missing from #1909 
Thank you for making this and I'm sorry that I forgot about it when I made #1909. This was a good sanity check

**Pull request closed without merging**
