### PR TITLE
Remove wrong Nullable annotation

### PR DESCRIPTION
**Pull request by Biospheere**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This Pull Requests removes a wrong @Nullable Annotation in the EmbedBuilder#addField method. The previous Annotation stated that both paramaters could be null. Instead the method throws an IllegalArgumentException.

### CODE REVIEW

**Comment by Andre601** [comment]
Sounds more like a bug?
There is `if(name == null && value == null) return this;` so I think it *should* be nullable and is therefore not wrong annotations.

**Comment by Biospheere** [comment]
But its && and not ||. So the method just returns the current embed without an exception if **both** are null. But the exception is currently thrown if one of the two paramters is null.

**Comment by MinnDevelopment** [comment]
No, these annotations are correct. You can set both values to null.

**Comment by MinnDevelopment** [comment]
This behavior is documented:

> @throws IllecalArgumentException [...] If only {@code name} or {@code value} is set. Both must be set.

**Comment by niklas2810** [comment]
> This behavior is documented:
> 
> > @throws IllecalArgumentException [...] If only {@code name} or {@code value} is set. Both must be set.

@MinnDevelopment 

The documentation does not reflect the actual API behavior: When both parameters are `null`, the method will simply return the current `EmbedBuilder` object without throwing an IllegalArgumentException. Link: https://github.com/DV8FromTheWorld/JDA/blob/fc59416fd9b024e1ac98da229f7726a28d1900e6/src/main/java/net/dv8tion/jda/api/EmbedBuilder.java#L774

Furthermore, I personally would find it more precise to document that both parameters "must not be null" instead of "must be set" in order to highlight that an empty String is a valid parameter.

**Pull request closed without merging**
