### PR TITLE
Adding support for setting and receiving streaming status.

### PR DESCRIPTION
**Pull request by jagrosh**
Added ability to detect Twitch streams in User#getCurrentGame()
Added ability to set Twitch stream in AccountManager#setStreaming(Game, Url)
Added Game and GameImpl to handle future game types

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
Okay so I have a few issues with this.
The syntax style/formatting doesn't match JDA. Please use whitespace.
Example: 
`if(user.getCurrentGame()==null?nextGame!=null:!user.getCurrentGame().equals(nextGame))`
vs
`if (user.getCurrentGame() == null ? nextGame != null : !user.getCurrentGame().equals(nextGame))`
This needs to be fixed across the entire commit.

The excessive amount of ternary statements is.. excessive. It makes the code really annoying to read, especially the one in EntityBuilder. Ternary is okay sometimes for simple stuff, but don't go nut

Lastly, you left the auto-generated @author statement in the License header. Please remove it :D

**Comment by jagrosh** [comment]
Alright, I fixed the whitespace and excessive number of ternary statements (found a couple extraneous ones too) - please double check that it's up-to-par with the rest of JDA

After testing, I found that the Discord Client only displays a user as "Streaming" if the provided URL matches the regex `^https?:\/\/(www\.)?twitch\.tv\/.+`; as such, the "streaming" status can only be set if the provided URL matches this regex as well.

Displaying streaming is client-side, which means users can still have a "Streaming" status in presence updates, even if the client doesn't show them as streaming. These are not differentiated in the Game object, but developers can use Game#isValidTwitchUrl to determine if a user's stream is displayed client-side.

**Comment by DV8FromTheWorld** [comment]
The class level Javadoc in Game is Guild's javadoc.

**Comment by DV8FromTheWorld** [comment]
I think we should also change the isValidTwitchUrl to isValidStreamingUrl due to Discord planning to support other stream sources.

**Comment by DV8FromTheWorld** [comment]
Lastly, make sure your braces are on newlines.

**Comment by DV8FromTheWorld** [comment]
If you have an if-statement that is more than 1 line please put it in brackets. Multiline ifs that don't use brackets can be confusing to read and easily introduce bugs into the code if something changes. Specifically I see this in the AccountManager and ReadyHandler.

**Comment by DV8FromTheWorld** [comment]
After those are fixed I'll merge. Everything else looks fine.

**Comment by DV8FromTheWorld** [comment]
Looks good. Merged! Should be build 267.

**Pull request merged**
