### PR TITLE
Add South Korea region

### PR DESCRIPTION
**Pull request by horyu1234**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Added South Korea region to Region enum class.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
I can't find a south korea region, are you sure this exists?

**Comment by Andre601** [comment]
Those regions don't exist.
There's only "south africa" and to my knowledge is that alreads in JDA.

**Comment by horyu1234** [comment]
@MinnDevelopment @Andre601 
South Korea server is exist.

Discord Screen
https://imgur.com/OQVTJCW

API Response(https://discordapp.com/api/voice/regions)
https://imgur.com/xAvzusr

**Comment by Andre601** [comment]
Are you using Canary?
Because on stable is this not available yet 
image

**Comment by horyu1234** [comment]
@Andre601 I'm using stable version of Discord (not using any test version)

**Comment by horyu1234** [comment]
@Andre601 This is my Discord version
image

**Comment by Andre601** [comment]
I also have this exact version, yet no matter if I edit a server or create one is this not available...
I believe you that this exists, but (at least for VIP) is it not 100% prooven that it is available for everyone.
But @MinnDevelopment has the final word here.

**Comment by kantenkugel** [comment]
Might be a geo-restricted region then? (only showing up in clients with south-korean ip)

**Comment by MCOfficer** [comment]
> 
> 
> Might be a geo-restricted region then? (only showing up in clients with south-korean ip)

Holy shit, you're correct. With a korean VPN i get this:
grafik

No idea why discord would do this, but it does exist.

**Comment by Andre601** [comment]
Now that you mention it, I can vaguely remember a comment in Discord datamining that south Korea was added as a new VC region.... But why it is region-locked is beyond me.

**Comment by caneleex** [comment]
> 
> 
>  But why it is region-locked is beyond me.

Maybe because other regions as Europe or America for example don't need South Korea region as it's kinda redundant?

**Comment by DV8FromTheWorld** [comment]
This type of restriction around South Korea is pretty common. Another example is how SK is handled in regards to League of Legends.

**Pull request merged**
