### PR TITLE
Added Send Messages in Threads to Permission enum

### PR DESCRIPTION
**Pull request by TheSuperGamer20578**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: #1887 

## Description

Adds Send Messages in Threads to the Permision Enum

### CODE REVIEW

**Comment by Xirado** [comment]
Already implemented in [v5](https://github.com/DV8FromTheWorld/JDA/blob/3e0d2f868e58af733eb50591ed19f601fdb20541/src/main/java/net/dv8tion/jda/api/Permission.java#L66)

**Comment by ToxicMushroom** [comment]
> Already implemented in [v5](https://github.com/DV8FromTheWorld/JDA/blob/3e0d2f868e58af733eb50591ed19f601fdb20541/src/main/java/net/dv8tion/jda/api/Permission.java#L66)
I don't feel like this is an addition that should be in some other feature's PR

**Comment by Tais993** [comment]
> 
> 
> > Already implemented in [v5](https://github.com/DV8FromTheWorld/JDA/blob/3e0d2f868e58af733eb50591ed19f601fdb20541/src/main/java/net/dv8tion/jda/api/Permission.java#L66)
> 
> I don't feel like this is an addition that should be in some other feature's PR

What do you mean with "other feature's PR"?
It makes sense to be in v5, v5 also adds full Thread support and more.

**Comment by Chew** [comment]
I still think permissions should be added here, even if not used internally. Knowing what permissions a user has regardless of the library's native support for them should be included in the LTS, as otherwise, they would not show up when querying a user or role's permissions, however they may be used.

**Comment by TheSuperGamer20578** [comment]
> By this logic, all the missing permissions should be here (manage events, play activities, etc)

I beleve the activity permission is already implemented
https://github.com/DV8FromTheWorld/JDA/blob/a35789442ba022c81ce9b5f62d5b6b9968e3895d/src/main/java/net/dv8tion/jda/api/Permission.java#L70

**Comment by DV8FromTheWorld** [comment]
I understand the argument, but we considered this to be a feature request. `v4` is closed to feature requests and will only be handling bugs.
`v5` has thread support, and if you wish to control permissions for threads then you need to update to it.

**Pull request closed without merging**
