### PR TITLE
Improve handling of Guild#getMaxEmotes

### PR DESCRIPTION
**Pull request by Shea4**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Due to what Joakim said here: https://github.com/DV8FromTheWorld/JDA/pull/1076#discussion_r312695975, I have improved the handling of Guild#getMaxEmotes, I know it's undocumented (At least I haven't found any documentation on it) but I thought I'd make the pr regardless as it follows quite similarly to Guild#getMaxBitrate

### CODE REVIEW

**Comment by caneleex** [comment]
Isn't maximum limit of emotes 250 emotes?

**Comment by Shea4** [comment]
With boosting yes

**Comment by 21Joakim** [comment]
The MORE_EMOJI feature gives the server 200 and with boosting you can get up to 250

**Comment by caneleex** [comment]
Oh, i see. My bad.

**Pull request merged**
