### PR TITLE
Support for parsing more presences

### PR DESCRIPTION
**Pull request by MinnDevelopment**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

## Description

Now you can also look at spotify details in presences.

Documentation is not very clear because discord hasn't updated their documentation yet.

Example JSON:
```json
{
    "assets": {
        "large_image":"spotify:8351a630c907a985143102b9466f4d2dab27ae9e",
        "large_text":"Lukas Graham"
    },
    "timestamps": {
        "start":1517831446419,
        "end":1517831683719
    },
    "name":"Spotify",
    "flags":48,
    "session_id":"09529cc3130f34d1530b142d33e08bce",
    "details":"7 Years",
    "state":"Lukas Graham",
    "type":2,
    "sync_id":"5kqIPrATaCc2LqxVWzQGbk",
    "party":{
        "id":"spotify:173609609221636096"
    }
}
```

### CODE REVIEW

**Comment by Sanduhr32** [comment]
That can be used for sending activity! Great.

**Comment by kantenkugel** [comment]
Waiting for official docs to finalize this? Would be nice to have proper flag documentation for example

**Comment by MinnDevelopment** [comment]
Since these fields aren't documented yet, I can't be sure they will stay this way.

**Comment by MinnDevelopment** [comment]
Future reference
`sync_id` - spotify track id `spotify:track:$sync_id`
`flags` - general information on which fields are present of the rich presence 
`session_id` - used by discord to sync listening along sessions

**Pull request merged**
