### PR TITLE
Added new RestAction operations for planned execution and async Request callback execution

### PR DESCRIPTION
**Pull request by MinnDevelopment**
This experiment will improve the JDA Requester system by adding a new Requester pool that will be used to execute request callbacks in an additional thread to counter possible deadlocks.
In addition I added new RestAction operations and documentation:
- `completeAfter(long, TimeUnit)`
- `submitAfter(long, TimeUnit [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit, Consumer<T> [, ScheduledExecutorService])`
- `queueAfter(long, TimeUnit, Consumer<T>, Consumer<Throwable> [, ScheduledExecutorService])`

More information on how these work can be found in the documentation.

> Note: This can still be changed.

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
Before merge, I'd like to have a listing of all ThreadPools in JDA.
Lets have a discussion about whether or not we should consider merging them into a singular pool

**Comment by MinnDevelopment** [comment]
A list of all executors:

File | Field | Type | Core Pool Size
--- | ----- | ----- | ---------------
AudioConnection | combinedAudioExecutor | SingleThreadScheduledExecutor | 1
JDAImpl | pool | ScheduledExecutorService | 2 (customizable)
RateLimiter | pool | ScheduledExecutorService | 5
Requester | pool | CachedThreadPool | -

**Comment by DV8FromTheWorld** [comment]
Besides the Executor in AudioConnection, are all pools dynamically expandable?
If they are, an argument could be made to combine all of the pools into one.

**Comment by DV8FromTheWorld** [comment]
Ignoring the AudioConnection pool which focuses on one very time sensitive thing, the other 3 pools work with the idea of expanding and contracting based on usage. But more so than that, they all hold different things besides perhaps the JDAImpl pool. I feel like the JDAImpl pool can and should be combined with one of the other two pools (Requester/RateLimiter) as its only use is for things *related* to the other two.

**Comment by DV8FromTheWorld** [comment]
@MinnDevelopment @Almighty-Alpaca thoughts?

**Comment by Almighty-Alpaca** [comment]
I'm fine with this for now. We can always test if merging the audio pools has a negative impact and decide about them later.

**Pull request merged**
