### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by Nick-kel**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [X] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This Pull Request fixes grammar mistakes in the GuildManager docs

### CODE REVIEW

**Comment by Andre601** [comment]
Changes towards the documentation of JDA should target the `docs/development` branch. You should correct that :)

**Comment by DV8FromTheWorld** [comment]
This will need to be rebased as it includes commits from other merged PRs in this commit.

**Comment by DV8FromTheWorld** [comment]
Bump

**Comment by Nick-kel** [comment]
Reverted the commits from other merged PRs in this commit

**Comment by MinnDevelopment** [comment]
You need to rebase not revert. The point is to *remove* the commit not revert its changes. I'll do it for you when I do the docs update.

**Comment by MinnDevelopment** [comment]
I cherry-picked your commit since you didn't base it on docs/development and don't allow me to force push your repo. https://github.com/DV8FromTheWorld/JDA/commit/b558a6ddd0b81c65abea31b89d82304669d9950c

**Pull request closed without merging**
