### PR TITLE
rename some userflags to match their new name

### PR DESCRIPTION
**Pull request by caneleex**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

for reference: discord/discord-api-docs#2011

maybe add "freezer" label to this pr until my pr in discord-api-docs repo gets merged/closed

### CODE REVIEW

**Comment by Owen1212055** [comment]
Partner was renamed as well, it is now called **Owner of a Partnered Server**.

**Comment by caneleex** [comment]
> 
> 
> Partner was renamed as well, it is now called **Owner of a Partnered Server**.

i don't see this change in my client yet

**Comment by RedstoneDaedalus** [comment]
Screen Shot 2020-08-28 at 2 04 34 PM
Latest canary update

**Comment by caneleex** [comment]
> 
> 
> Screen Shot 2020-08-28 at 2 04 34 PM
> Latest canary update

got this update a few seconds ago, i'll change it too then

**Comment by RedstoneDaedalus** [comment]
Wait until it's on stable, discord might change it again.

**Comment by caneleex** [comment]
> 
> 
> Wait until it's on stable, discord might change it again.

is "Early Verified Bot Developer" on stable yet then?

**Comment by Andre601** [comment]
Seems like it gets changed to "Partnered server Owner" now
https://github.com/DJScias/Discord-Datamining/commit/f5354f14ded647fb83d0b90a4f172be118e078b2#commitcomment-41866202

**Comment by Andre601** [comment]
Just so I won't missunderstand anything... The internal names of Discord also stayed the same?
Or did there change something?

Because looking at the flags would it now be weird to have `VERIFIED_DEVELOPER` return `Early Verified Bot Developer`, so is there like any (un)official refernce we could look at for clarification?

I only have https://github.com/vDelite/DiscordLists/blob/master/flags.md which isn't up-to-date.

**Comment by Sanduhr32** [comment]
It shouldn't matter if JDA has the exact names copied for its user flag enum. The names of the entries should have a matching meaning and also matching descriptions (displayed hover text) imo.
If Discord has an official name for them in their API Docs then JDA will most likely copy them.
@Andre601

**Comment by Andre601** [comment]
It should matter as it helps with maintaining and understanding it.
Otherwise could we just have `FLAG_1`, `FLAG_2`, etc as long as the values are right...

**Comment by caneleex** [comment]
you think about stuff too much

**Comment by MinnDevelopment** [comment]
Renaming the enum constants because of stupid discord branding is not necessary.

**Review by MinnDevelopment — APPROVED** [review]

**Pull request merged**
