### PR TITLE
Rewrite decompression to use less allocations and regrows

### PR DESCRIPTION
**Pull request by Shredder121**
The old code used a `StringBuilder` with the default capacity and made a new String for each 128 byte chunk.

### CODE REVIEW

**Comment by kantenkugel** [comment]
I am not entirely sure if this system is that much faster, as there might be a lot of array copies to enlarge the buffer of the ByteArrayOutputStream depending on the size of the decompressor output

**Comment by Shredder121** [comment]
At least the greater initial size limits the regrows, as was seen in the old StringBuilder approach, and actually doing the string coding at the end is a lot better for if there are multi byte characters, and string coders that might do validation?
I've been running it for some time, but forgot to take screenshots of my sessions.
You can take a look at my branch `decompresser-test` if you wish.

**Comment by MinnDevelopment** [comment]
Would you please update this to follow our code style in bracket placing.

**Comment by Shredder121** [comment]
Sorry my bad, I will 😅

**Comment by Shredder121** [comment]
With only 6 guilds and rebuilding the shard it's apparent all those calls to the string constructor contribute to 1) more cpu time than necessary and 2) more allocations.
I don't have any hard evidence to support whether multi-byte characters would cause issues or not, but I suppose it would be pretty bad luck if it poses a problem in the real world, if those happen to align with the 128 byte chunks.

| CPU call tree | Allocation call tree |
|---------------|----------------------|
| ![CPU Call Tree][cpu] | ![Allocation Call Tree][mem]

[cpu]: https://user-images.githubusercontent.com/4105066/29750882-0acb8b6e-8b48-11e7-9e3a-8256856293d8.png
[mem]: https://user-images.githubusercontent.com/4105066/29750886-1e26307e-8b48-11e7-894c-bc0115ded832.png

**Comment by Shredder121** [comment]
(the last repush was just some import cleanup)

**Comment by MinnDevelopment** [comment]
@Shredder121 Thank you for your contribution

**Comment by Shredder121** [comment]
:+1:

**Pull request merged**
