### PR TITLE
Switched guild collection in EmoteImpl to Set

### PR DESCRIPTION
**Pull request by MinnDevelopment**
now remove emotes from guild maps properly.

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
As we spoke about in the JDA Guild, I'd like to test to make sure this actually works as expected if possible.

**Comment by kantenkugel** [comment]
There is another patch incoming that switches to single guild per emote. But that one needs this to merged before (bug-fix)

**Comment by MinnDevelopment** [comment]
According to night, emotes can not share two guilds.

**Comment by MinnDevelopment** [comment]
The current code has been on Momo for 2 hours without any unexpected behavior and all emotes returned by JDA are available to the bot.

**Comment by DV8FromTheWorld** [comment]
I'm assuming that means that this should be working, yes?

**Comment by MinnDevelopment** [comment]
Yes this *should* be working according to the data my bot has collected.

**Comment by DV8FromTheWorld** [comment]
:+1:

**Pull request merged**
