### PR TITLE
Moved Widgets related classes into the .entities packages instead of nesting in WidgetUtil

### PR DESCRIPTION
**Pull request by RealYusufIsmail**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes : #2294

## Description

Moved Widget related classes instead of them being in WidgetUtil

### CODE REVIEW

**Comment by Almighty-Satan** [comment]
I don't think these enums should be moved as they are only used by methods in the `WidgetUtil` class.

**Comment by freya022** [comment]
> I don't think these enums should be moved as they are only used by methods in the `WidgetUtil` class.

They will be used in user code though, so it makes sense for the user to see `Widget.WidgetTheme` instead of `WidgetUtil.WidgetTheme`

**Comment by Almighty-Satan** [comment]
> They will be used in user code though, so it makes sense for the user to see `Widget.WidgetTheme` instead of `WidgetUtil.WidgetTheme`

By that logic shouldn't then all methods in `WidgetUtil` also be moved to the `Widget` class?

**Comment by RealYusufIsmail** [comment]
> > They will be used in user code though, so it makes sense for the user to see `Widget.WidgetTheme` instead of `WidgetUtil.WidgetTheme`
> 
> 
> 
> By that logic shouldn't then all methods in `WidgetUtil` also be moved to the `Widget` class?

Should I move everything from widget utils into widget

**Comment by MinnDevelopment** [comment]
Thanks, but we think this can stay where it is.

**Pull request closed without merging**
