### PR TITLE
Move presence information into guild presence object

### PR DESCRIPTION
**Pull request by MinnDevelopment**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This should reduce the memory footprint of `MemberImpl` a tiny bit when presence caching is disabled.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
The reason this is labeled as breaking is because I also renamed the `CacheFlag` for activity which wasn't representing of its actual usage.

**Comment by Andre601** [comment]
Does this affect any end user code?

**Comment by MinnDevelopment** [comment]
@Andre601 only people who use v4 alpha and made use of `CacheFlag.PRESENCE`. It was renamed to `CacheFlag.ACTIVITY`.

**Comment by MinnDevelopment** [comment]
Memory breakdown per member:

| Scenario | Memory Footprint (64bit) | Meaning |
|-|-|-|
| Full Cache | 72 = 48 + 24 | Member + GuildPresence |
| Disabled Presence | 48 | Member + Empty (amortized) |
| Before patch | 56 | Member |

> I used `java.lang.instrument.Instrumentation` to calculate these values

When the new variable is added and all cache is enabled we increase the total memory footprint of member by 16 bytes (object header). With the cache disabled we improve by 8 bytes.
Now we have to consider whether this is worth it or not.

**Pull request closed without merging**
