### PR TITLE
Add check and recovery for missing self members

### PR DESCRIPTION
**Pull request by MinnDevelopment**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [ ] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Very rarely, discord sends us guilds with missing self members. This pull request adds a check for this case and a recovery attempt. We make a gateway request to load the self member after creating the guild object, which should in theory be able to recover the self member.

### CODE REVIEW

**Comment by DV8FromTheWorld** [comment]
I wonder if we should use the GuildLock system (or another form of waiting) before releasing the Guild for use if we need to re-request the self-member 🤔

**Comment by MinnDevelopment** [comment]
This is a pretty rare API error which might not even recover successfully. I don't think we should prevent ready event because of a buggy guild initialization.

**Comment by DV8FromTheWorld** [comment]
Where are we on this? Are we confident enough to go ahead and merge this in for inclusion in the v4 LTS?

**Comment by MinnDevelopment** [comment]
Should be good to go.

**Pull request merged**
