### PR TITLE
Implement Autocomplete

### PR DESCRIPTION
**Pull request by aasmart**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [X] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This introduces Discord's upcoming **autocomplete** feature for Slash Commands. This also features a refactor of the interaction hierarchy to accommodate for the new interaction type. 

### Using the Interaction
`OptionData` can now have autocomplete enabled with `option.setAutoComplete(true)`. This can **only** be enabled on options with types, Integer, Number, or String. Once autocomplete is enabled for an option, you may not add choices (It will not enable if choices are already present on the option).

To respond with choices, you can use the following:
```java
@Override
public void onCommandAutoComplete(@NotNull CommandAutoCompleteEvent event)
{
    event.respondChoices(
            new Command.Choice("choice-1", "one"),
            new Command.Choice("choice-2", "two"),
            new Command.Choice("choice-3", "three")
    ).queue();
}
```
You can also get the option the user is currently focused on with `event.getFocusedOption()`

### Discussion Points
* This implementation adds the `focused` value to OptionMapping, which I'm not sure should be present there or elsewhere
* `InteractionHook` was split into `InteractionHook` and `ChannelInteractionHook`. However `ChannelInteractionHook` cannot extend `InteractionHook`
* `InteractionCallbackAction` and `ChannelInteractionCallbackAction` are kind of janky because of the former
* `CommandAutoCompleteInteraction` and `CommandInteraction` share a large amount of identical code

### CODE REVIEW

**Comment by AfonsoHackers** [comment]
Is this ever going to be implemented?

**Comment by MinnDevelopment** [comment]
@AfonsoHackers yes.

**Comment by AfonsoHackers** [comment]
> 

The question is when I suppose?

**Comment by MinnDevelopment** [comment]
Superseded by #1971

**Pull request closed without merging**
