### PR TITLE
Update Features list for Guild#getFeatures()

### PR DESCRIPTION
**Pull request by Andre601**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description
Updates the docs for `Guild#getFeatures()` with the latest set from the Discord docs.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Please base your changes on `docs/development` instead.

**Comment by Andre601** [comment]
Not sure how I could refactor that now without making a new branch and PR.

**Comment by MinnDevelopment** [comment]
```sh
git checkout -b patch-new upstream/docs/development # Create new branch (don't worry we just do this to create a new pointer)
git cherry-pick fix/update-guild-features-docs # Take last commit from previous branch
git push -f origin patch-new:fix/update-guild-features-docs # Force push new branch ontop of previous branch
```

**Comment by Andre601** [comment]
`fatal: bad revision 'fix/update-guild-features-docs'` when doing cherry-pick

**Comment by MinnDevelopment** [comment]
Worked fine for me.

**Comment by MinnDevelopment** [comment]
I think its time to replace this list with a link to the docs:

`<a target="_blank" href="https://discord.com/developers/docs/resources/guild#guild-object-guild-features">List of Features</a>`

**Comment by Andre601** [comment]
Found the culprit.
Had to first fetch the changes from the branch, since this PR changed it somehow...

Will now work on linking to the docs.

**Comment by Andre601** [comment]
Is this `@return` description actually true?
> Never-null, unmodifiable Set containing all of the Guild's features.

I would image this being at least a possibly-empty Set, considering that there is no guarantee that a Guild even has one of the currently listed features (Each requires either manual enabling or unlocking)

**Comment by MinnDevelopment** [comment]
An empty set is also not null and unmodifiable, so this description is correct.

An empty set:

- [x] unmodifiable
- [x] not null
- [x] contains all of the guilds features (none)

**Pull request merged**
