### PR TITLE
Event disabling

### PR DESCRIPTION
**Pull request by meowingtwurtle**
I saw this on your TODO list in the Discord, so I tried to implement it.

### CODE REVIEW

**Comment by DinosParkour** [comment]
You should follow this lib's formatting to begin with (`{` in a new line etc)

**Comment by meowingtwurtle** [comment]
Sorry! Forgot about that. My IDE does the way in the commits by default :P

**Comment by meowingtwurtle** [comment]
Fixed

**Comment by meowingtwurtle** [comment]
Told was to be rejected by DV8 because it still requires time/resources to construct/parse event.

**Pull request closed without merging**
