### PR TITLE
Multiple Embed-Related Fixes

### PR DESCRIPTION
**Pull request by jagrosh**
added convenience method editMessage(MessageEmbed) to Message
implemented convenience method in MessageImpl
combined setUrl into setTitle in EmbedBuilder
allow use of more TemporalAccessor by allowing a default zone
remove setVideo and setProvider
check both urls in setAuthor
no NPE for null field, and field docs have warning on limit (25)

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
This will be on the waiting list until we merged JavaDocs.

**Comment by Wiildanimal** [comment]
No idea if this is the right place, but:

- add removeField(String title)
- add setFieldValue(String title, String value)
- add setFieldInline(String title, boolean inline)

I made this little class because those aren't implemented:  https://hastebin.com/xitosecari.java

**Comment by Almighty-Alpaca** [comment]
@Wiildanimal how would these methods behave if there are multiple fields with the same title?

**Comment by Wiildanimal** [comment]
@Almighty-Alpaca In my CustomEmbedBuilder I have it so that it does it for all fields with that name, but tbh that's for you guys to decide.

**Comment by MinnDevelopment** [comment]
@jagrosh this needs to be rebased to take the new JavaDoc changes into account.
In addition it must follow the JavaDoc formatting template.

**Comment by jagrosh** [comment]
Replaced by #259

**Pull request closed without merging**
