### PR TITLE
added User-Commands and Message-Commands

### PR DESCRIPTION
**Pull request by Lex305**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [ ] I have checked the PRs for upcoming features/bug fixes.
- [X] I have read the [contributing guidelines][contributing].

### Changes

- [X] Internal code
- [X] Library interface (affecting end-user code) 
- [X] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Adds the new User-Commands and Message-Commands.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Duplicate of #1765

**Comment by Lex305** [comment]
I don't really understand why this a duplicate is?

**Comment by MinnDevelopment** [comment]
It is a duplicate because the linked PR already adds user and message commands (which are context menus).

**Comment by freya022** [comment]
The user and message context commands feature PR was already proposed by aasmart and put on hold for JDA 5

**Pull request closed without merging**
