### PR TITLE
Made a few methods in MessageImpl synchronized

### PR DESCRIPTION
**Pull request by MinnDevelopment**
This should fix issues with concurrent calls to the modified methods.

### CODE REVIEW

**Comment by meowingtwurtle** [comment]
Wouldn't the setters also have to be synchronized for this to actually have any effect?
Because the get and set calls could still interleave.

**Comment by meowingtwurtle** [comment]
A better solution would be to have a lock that is only locked and released if subcontent is null, otherwise just return subcontent without locking.

**Comment by MinnDevelopment** [comment]
What setters are you talking about exactly?

**Comment by meowingtwurtle** [comment]
setContent() mainly

**Comment by MinnDevelopment** [comment]
`setContent` sets the raw content returned by `getRawContent`.
`getContent` however overrides  the raw content and provides a content without the discord formats like `<@86699011792191488>` for mentions and instead replaces them with `@Minn`.
That new content with stripped formats is then saved as `subContent`.
`getStrippedContent` does something similar for markdown formatting.

**Comment by MinnDevelopment** [comment]
The `setContent` method is only used by internal builders and should never be used when the user accesses the Message.

**Comment by meowingtwurtle** [comment]
Okay, sorry I misunderstood what the setter methods were for!

**Pull request merged**
