### PR TITLE
Add missing null checks in HttpRequestEvent

### PR DESCRIPTION
**Pull request by napstr**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

There are several guidelines you should follow in order for your
  Pull Request to be merged.

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

> It is sometimes better to include more changes in a single commit. 
  If you find yourself having an overwhelming amount of commits, you
  can **rebase** your branch.

### Pull Request

Response#rawResponse is a nullable field and some methods in the HttpRequestEvent don't treat it like it is (though some do, like HttpRequestEvent#getResponseHeaders). This adds the missing checks.

### CODE REVIEW

**Comment by kantenkugel** [comment]
isn't this a bit too many null-checks? can request/response itself be null?

**Comment by MinnDevelopment** [comment]
okhttp3.Response can be null but I don't believe Request or Response can be null

**Comment by napstr** [comment]
HttpRequestEvent#getRequestHeaders a ton of methods in the class are checking it for null so I assumed that its nullable.

**Comment by napstr** [comment]
I can but then again my main goal here is to fix the NPE not spend time checking the behaviour of other variables. If you don't want the nullcheck even though it is in style with the rest of the class please let me know and I'll remove it - I can't tell from the feedback so far if that decision has been reached yet by JDA staff.

Personally I've adopted `@Nonnull` and `@Nullable` annotations at many places to deal with not having to assume things. If that's a thing the JDA team would be interested in I'd be happy to add those as they create lasting value. Otherwise, the next person touching this has to do the research again, etc. Feel free to ping me in the Discord if it's a thing that grabs your interest.

**Comment by MinnDevelopment** [comment]
The jsr-305 annotations might be getting more attention in JDA 3.5 but we would make that decision when the time is right. In this PR this is not needed.

**Comment by napstr** [comment]
How about this?

**Pull request merged**
