### PR TITLE
Update repo Maven

### PR DESCRIPTION
**Pull request by tristiisch**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [ ] Library interface (affecting end-user code) 
- [x] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

Replace this sentence with general description of what your Pull Request does.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
This is an incorrect change. The repository is jcenter.

**Comment by tristiisch** [comment]
@MinnDevelopment the jcenter is forbidden but this repo works. So fix it or pull my request please.

**Comment by MinnDevelopment** [comment]
https://jcenter.bintray.com/net/dv8tion/JDA/4.1.1_108/ this URL works completely fine. There must be some issue on your end if you see forbidden. Make sure you're actually using https. The URL you're suggesting in your pull request doesn't work as the transitive dependencies of JDA are not included in that repo:

- https://jcenter.bintray.com/club/minnced/opus-java/1.0.4/
- https://dl.bintray.com/dv8fromtheworld/maven/club/minnced/opus-java/1.0.4/

**Comment by duncte123** [comment]
> the jcenter is forbidden but this repo works. So fix it or pull my request please.

Make sure that you're using https for jcenter if it gives a 403 response

**Comment by tristiisch** [comment]
`		<dependency>
			<groupId>net.dv8tion</groupId>
			<artifactId>JDA</artifactId>
			<version>[4.1.1_108,)</version>
		</dependency>`
Okay, it wasn't working for when I made the sweater request, but this isn't working and it's not normal.

**Comment by DManstrator** [comment]
Did you look at the version you wrote there? That isn't valid at all.

**Pull request closed without merging**
