### PR TITLE
Allow all guild channels to be mentioned

### PR DESCRIPTION
**Pull request by nikammerlaan**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

## Description

Allows all guild channels to be mentioned.

### CODE REVIEW

**Comment by DManstrator** [comment]
Slight Note: A `VoiceChannel` is also a `GuildChannel`. Earlier, it was not possible to mention them, at least on Desktop Versions (it worked at least on Android). As of now, it seems that Discord really added VoiceChannel mentions so this should work now.

**Comment by nikammerlaan** [comment]
> Slight Note: A `VoiceChannel` is also a `GuildChannel`. Earlier, it was not possible to mention them, at least on Desktop Versions (it worked at least on Android). As of now, it seems that Discord really added VoiceChannel mentions so this should work now.

Mentioning voice channels is actually the reason I made this PR :p They were mentionable before, they just were kinda useless

**Comment by DManstrator** [comment]
> Mentioning voice channels is actually the reason I made this PR :p They were mentionable before, they just were kinda useless

Out of interest, do you know when Discord released that feature? I remember talking to somebody about that 3 months ago when this wasn't possible yet. I guess not for long since there is no UI support for it so far.

**Comment by Andre601** [comment]
> > Mentioning voice channels is actually the reason I made this PR :p They were mentionable before, they just were kinda useless
> 
> Out of interest, do you know when Discord released that feature? I remember talking to somebody about that 3 months ago when this wasn't possible yet. I guess not for long since there is no UI support for it so far.

Since a few days.
Mentioned voice and stage channels now display that speaker icon instead of a #.
It's afaik still canary only

**Comment by DManstrator** [comment]
> It's afaik still canary only

I'm not using a canary version and mentioning Voice Channels work for me. Can't tell for Store Channels since I'm not in a server having one. Just no UI support or did you mean that this already works in Canary?

**Comment by Chew** [comment]
You can mention store channels. It's clickable, but it's #Channel Name, not a store icon.
image

**Comment by nikammerlaan** [comment]
>  Can't tell for Store Channels since I'm not in a server having one. 

Store channels were already mentionable within JDA, so it's not really important

**Comment by Andre601** [comment]
Not 100% sure if that's important to the overall design of a VC mention, but on client you use `#!` to auto-complete VC.

I assume the raw value is still the same as with text channels tho? Docs don't suggest any change on that matter but I'm not sure, so perhaps someone should quickly check if it's right.

**Comment by nikammerlaan** [comment]
> Not 100% sure if that's important to the overall design of a VC mention, but on client you use `#!` to auto-complete VC.
> 
> I assume the raw value is still the same as with text channels tho? Docs don't suggest any change on that matter but I'm not sure, so perhaps someone should quickly check if it's right.

It's still the same

**Review by DV8FromTheWorld — APPROVED** [review]

**Pull request merged**
