### PR TITLE
Make GenericGuildVoiceUpdateEvent public

### PR DESCRIPTION
**Pull request by averen**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

GenericGuildVoiceUpdateEvent is currently package-private, which obviously is a mistake for an event.

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Whats wrong with using `GuildVoiceUpdateEvent`? The interface exists for this exact purpose and is also in `ListenerAdapter`.

**Comment by averen** [comment]
I must've overlooked `GuildVoiceUpdateEvent`, but I'm curious as to why it is intended behavior.

**Comment by MinnDevelopment** [comment]
It is intended behavior because you should listen for the `GuildVoiceUpdateEvent` and not the `GenericGuildVoiceUpdateEvent`. The latter isn't even in `ListenerAdapter` and that hasn't been addressed by this PR either. There really is no point to making this public, it only exists to reduce duplicate code.

**Comment by averen** [comment]
Fair enough. I assumed since it was the direct parent of `GuildVoiceJoinEvent` and `GuildVoiceMoveEvent` that it could be used as a cast.

**Comment by MinnDevelopment** [comment]
You can cast to the interface as well, its also a direct parent.

**Pull request closed without merging**
