### PR TITLE
Fixing parameter pass-through of Presence#setGame and Presence#setIdle

### PR DESCRIPTION
**Pull request by kantenkugel**
Fixes wrong parameters of Presence#setGame and Presence#setIdle to the 2-arg methods. 
Fixes setting game and idle via Presence

Fixes #482

### CODE REVIEW

**Comment by kantenkugel** [comment]
waiting with merge... seems like i missed something

**Comment by binaryoverload** [comment]
`setStatus` is missing :P

**Comment by kantenkugel** [comment]
yea im gonna drop this one in favor of #482

**Comment by binaryoverload** [comment]
👍

**Pull request closed without merging**
