### PR TITLE
Mark every deprecation for removal

### PR DESCRIPTION
**Pull request by Alf-Melmac**
## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [ ] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

## Description

In preparation for the v4 LTS, this PR marks each deprecated location for removal at the latest in 5.0.0.

### CODE REVIEW

**Review by DV8FromTheWorld — APPROVED** [review]

**Review by MinnDevelopment — APPROVED** [review]
This would make more sense as a PR against docs/development though

**Comment by DV8FromTheWorld** [comment]
I agree, however the `docs/development` branch needs to have `development` merged into it first otherwise this PR will create a merge commit for 15+ other commits.

**Comment by Alf-Melmac** [comment]
I can open a new PR targeting docs/dev if you want

**Comment by Alf-Melmac** [comment]
-> #1842

**Pull request closed without merging**
