### PR TITLE
Introduce better methods to load members

### PR DESCRIPTION
**Pull request by MinnDevelopment**
[contributing]: https://github.com/DV8FromTheWorld/JDA/wiki/5%29-Contributing

## Pull Request Etiquette

- [x] I have checked the PRs for upcoming features/bug fixes.
- [x] I have read the [contributing guidelines][contributing].

### Changes

- [x] Internal code
- [x] Library interface (affecting end-user code) 
- [ ] Documentation
- [ ] Other: \_____ 

Closes Issue: NaN

## Description

This introduces better methods for loading members on a guild.

### Example

**Current:**
```java
guild.retrieveMembers().thenRun(() -> {
  List<Member> members = guild.getMembers();
  members.forEach(System.out::println);
  guild.pruneMemberCache(); // manually clear the cache again
});

guild.retrieveMembers().thenRun(() -> {
  List<Member> members = guild.getMembers();
  System.out.println(members.size());
  guild.pruneMemberCache(); // manually clear the cache again
});
```
**New:**
```java
guild.loadMembers(System.out::println); // only adds members to cache which the policy accepts
guild.loadMembers().onSuccess((members) -> {
  System.out.println(members.size());
});
```

### CODE REVIEW

**Comment by MinnDevelopment** [comment]
Unfortunately, the overloads seem to result in "ambiguous calls" which makes `guild.loadMembers((x) -> System.out.println(x));` a compiler error. This could be fixed by using different method names, open for suggestions.

**Comment by Andre601** [comment]
I could come up with a name idea, if you can quickly list what the loadMembers method will actually do next to getting the members obviously.

**Comment by MinnDevelopment** [comment]
I'm thinking of renaming `loadMembers(Predicate)` to `findMembers(Predicate)` which seems more accurate and solves the name conflict. The methods would work like this:

`loadMembers(): Task<List<Member>>` load all members into a list 
`findMembers(Predicate): Task<List<Member>>` load all members but only retain the ones that match the filter
`loadMembers(Consumer): Task<Void>` load all members but don't put them into a list, instead use a callback for each member like a forEach method

**Comment by Andre601** [comment]
Seems like a good idea to make.

**Pull request merged**
